import { Job, Bid, Worker, ChatMessage } from './types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Fix leaking kitchen tap',
    description: 'Kitchen tap has been leaking for 2 days. Need urgent repair. Standard single-lever mixer tap.',
    category: 'plumbing',
    budget: 500,
    budgetType: 'negotiable',
    status: 'open',
    location: { lat: 13.0827, lng: 80.2707, address: 'Anna Nagar, Chennai' },
    images: [],
    customerId: 'c1',
    customerName: 'Priya M.',
    createdAt: '2026-03-28T08:00:00Z',
    distance: 1.2,
    bidCount: 3,
  },
  {
    id: '2',
    title: 'Wall painting - 2BHK apartment',
    description: 'Need interior painting for full 2BHK apartment. Around 900 sq ft. Prefer Asian Paints.',
    category: 'painting',
    budget: 15000,
    budgetType: 'fixed',
    status: 'open',
    location: { lat: 13.0604, lng: 80.2496, address: 'T Nagar, Chennai' },
    images: [],
    customerId: 'c2',
    customerName: 'Rajan K.',
    createdAt: '2026-03-28T07:30:00Z',
    distance: 3.5,
    bidCount: 5,
  },
  {
    id: '3',
    title: 'AC repair - not cooling',
    description: 'Split AC 1.5 ton not cooling properly. Gas might need refilling. Brand: Voltas.',
    category: 'repair',
    budget: 1200,
    budgetType: 'negotiable',
    status: 'open',
    location: { lat: 13.0478, lng: 80.2089, address: 'Vadapalani, Chennai' },
    images: [],
    customerId: 'c3',
    customerName: 'Suresh R.',
    createdAt: '2026-03-28T09:15:00Z',
    distance: 0.8,
    bidCount: 2,
    isInstant: true,
  },
  {
    id: '4',
    title: 'Deliver 50 boxes to warehouse',
    description: 'Need to move 50 cardboard boxes from shop to warehouse. Distance around 5km. Need vehicle.',
    category: 'delivery',
    budget: 2000,
    budgetType: 'fixed',
    status: 'open',
    location: { lat: 13.0878, lng: 80.2785, address: 'Aminjikarai, Chennai' },
    images: [],
    customerId: 'c4',
    customerName: 'Meena S.',
    createdAt: '2026-03-28T06:45:00Z',
    distance: 5.1,
    bidCount: 1,
  },
  {
    id: '5',
    title: 'Electrical wiring for new room',
    description: 'Need complete electrical wiring for a newly constructed room. 3 lights, 2 fans, 4 sockets.',
    category: 'electrical',
    budget: 3500,
    budgetType: 'negotiable',
    status: 'open',
    location: { lat: 13.0674, lng: 80.2376, address: 'Ashok Nagar, Chennai' },
    images: [],
    customerId: 'c5',
    customerName: 'Karthik V.',
    createdAt: '2026-03-28T10:00:00Z',
    distance: 2.3,
    bidCount: 4,
  },
];

export const mockBids: Bid[] = [
  {
    id: 'b1', jobId: '1', workerId: 'w1', workerName: 'Murugan P.',
    workerRating: 4.8, workerReviewCount: 124, price: 450,
    timeEstimate: '1 hour', message: 'I can fix this quickly. Have all tools ready.',
    status: 'pending', createdAt: '2026-03-28T08:30:00Z',
  },
  {
    id: 'b2', jobId: '1', workerId: 'w2', workerName: 'Senthil K.',
    workerRating: 4.5, workerReviewCount: 89, price: 600,
    timeEstimate: '2 hours', message: 'Will replace the full tap if needed. Warranty included.',
    status: 'pending', createdAt: '2026-03-28T08:45:00Z',
  },
  {
    id: 'b3', jobId: '1', workerId: 'w3', workerName: 'Rajesh M.',
    workerRating: 4.2, workerReviewCount: 45, price: 400,
    timeEstimate: '1.5 hours', message: 'Experienced plumber. Can come immediately.',
    status: 'pending', createdAt: '2026-03-28T09:00:00Z',
  },
];

export const mockWorker: Worker = {
  id: 'w1',
  name: 'Murugan P.',
  phone: '+91 98765 43210',
  role: 'worker',
  rating: 4.8,
  reviewCount: 124,
  skills: ['plumbing', 'repair'],
  experience: '8 years',
  serviceRadius: 10,
  isVerified: true,
  completedJobs: 312,
  earnings: 185000,
  location: { lat: 13.08, lng: 80.27 },
};

export const mockChatMessages: ChatMessage[] = [
  { id: 'm1', senderId: 'c1', text: 'Hi, can you come today?', timestamp: '2026-03-28T09:00:00Z', isRead: true },
  { id: 'm2', senderId: 'w1', text: 'Yes madam, I can reach by 11 AM', timestamp: '2026-03-28T09:02:00Z', isRead: true },
  { id: 'm3', senderId: 'c1', text: 'Great! Please bring extra washers too', timestamp: '2026-03-28T09:05:00Z', isRead: true },
  { id: 'm4', senderId: 'w1', text: 'Sure, I will bring everything needed 👍', timestamp: '2026-03-28T09:06:00Z', isRead: false },
];
